on: 
  workflow_dispatch: {}
  schedule:
    # Makes commit(s) at 9am daily
    # Change to whatever cron expression you like
    - cron: "0 5 * * *"

jobs:
  lit-job:
    env:
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    runs-on: ubuntu-latest
    name: A job to get you lit
    steps:
      - uses: actions/checkout@v3
      - name: make commits
        # Uses GitHub action defined in https://github.com/FredaXin/gitlit
        uses: FredaXin/gitlit@main
        with:
          # Defines the range of number of commits
          # Change to your desierd lower and upper bound
          lower-bound: 10
          upper-bound: 100
          # Change to your GitHub username
          user-name: X-itachi-X
          # Change to your email used for GitHub account
          user-email: ankitprakash2909@gmail.com
